### ISSUE TITLE
header: Inject field doc-comments

### ISSUE THREAD

**Issue by ryneeverett** [djmitche/ffizz#43]
Could we extract doc-comments for fields and inject them into the generated headers in the appropriate place to avoid duplication?

**Comment by djmitche** [comment]
At the moment, the tool is basically doing textual substitution, so I wouldn't want to make it too smart about "the appropriate place" -- I don't want to get into parsing code.

I suppose one of the examples that inspired this issue is
```rust
#[ffizz_header::item]
#[ffizz(order = 500)]
/// ***** TCUda *****
///
/// TCUda contains the details of a UDA.
///
/// ```c
/// typedef struct TCUda {
///   // Namespace of the UDA.  For legacy UDAs, this may have a NULL ptr field.
///   struct TCString ns;
///   // UDA key.  Must not be NULL.
///   struct TCString key;
///   // Content of the UDA.  Must not be NULL.
///   struct TCString value;
/// } TCUda;
/// ```
#[repr(C)]
#[derive(Default)]
pub struct TCUda {
    /// Namespace of the UDA.  For legacy UDAs, this may have a NULL ptr field.
    pub ns: TCString,
    /// UDA key.  Must not be NULL.
    pub key: TCString,
    /// Content of the UDA.  Must not be NULL.
    pub value: TCString,
}
```

Honestly, my first reaction is to just omit the docstrings in the Rust struct. The _primary_ purpose of this file is to generate a C interface, and TCUda would not be much used in other Rust code. Probably comments and docstrings in the Rust type should only be used for Rust-specific things like safety warnings.

That said, one way I can think of for accomplishing this is to invent a simple kind of "macro substitution":

```rust
#[ffizz_header::item]
#[ffizz(order = 500)]
/// ...
/// ```c
/// typedef struct TCUda {
///   // #[ffizz_header:include(name="TCUda.ns")]
///   struct TCString ns;
///   // #[ffizz_header:include(name="TCUda.key")]
///   struct TCString key;
///   // #[ffizz_header:include(name="TCUda.value")]
///   struct TCString value;
/// } TCUda;
/// ```
#[repr(C)]
#[derive(Default)]
pub struct TCUda {
    #[ffizz_header:define(name="TCUda.ns")]
    /// Namespace of the UDA.  For legacy UDAs, this may have a NULL ptr field.
    pub ns: TCString,
    #[ffizz_header:define(name="TCUda.key")]
    /// UDA key.  Must not be NULL.
    pub key: TCString,
    #[ffizz_header:define(name="TCUda.value")]
    /// Content of the UDA.  Must not be NULL.
    pub value: TCString,
}
```

However, that's not much shorter or more readable. It'd also be a bit hard to implement, since we'd have to parse the `#[..]` syntax within the doc comment.

**Comment by ryneeverett** [comment]
> I don't want to get into parsing code

I guess it depends on what you mean by "get into parsing". I was thinking it might be possible to do this in post-processing at a relatively high level of abstraction -- parse both the rust file and the generated header file into AST's (using existing tooling), extract the doc-comments from the rust AST, inject into the header AST, etc.

> Honestly, my first reaction is to just omit the docstrings in the Rust struct. The primary purpose of this file is to generate a C interface...

I can't speak to that particular file but it strikes me that several of the types exposed in the header file are also used extensively in taskchampion, no? Seems a shame in general to have to choose between documenting in one language or the other or duplication. Even if it's not such a dilemma in taskwarrior, wouldn't it potentially be more of a dilemma in other projects?

**Comment by djmitche** [comment]
That's pretty much what I mean by "get into parsing"! It's tricky since this is implemented as a macro which has only limited visibility into the Rust code.

Most of the types in Taskchampion are opaque types, so there are no C struct fields to comment on. `TCUda`, above, exists only for the purposes of the C API.

I'm not sure there are situations where one has "to choose between documenting in one language or the other or duplication." Did you have a specific example?

**Comment by ryneeverett** [comment]
>  It's tricky since this is implemented as a macro which has only limited visibility into the Rust code.

My idea was not to try to do it within the macro but to post-process after generating the header file, if that makes sense.

> I'm not sure there are situations where one has "to choose between documenting in one language or the other or duplication." Did you have a specific example?

No, I suppose there are no examples in taskwarrior because the taskchampion-lib is entirely designed as an integration layer. Is such a layer always necessary for inter-language integration? I have no experience in this area.

**Comment by djmitche** [comment]
I think that's the approach that ffizz supports, in general. I've had a hard time finding what's "typical" for this sort of thing, so it's hard to say.

I think at the moment we don't have enough information to decide if this is a good idea.  Let's revisit if it turns out to be problematic.
